-- AlterTable
ALTER TABLE "Proposta" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dataCriacao" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dataResposta" TIMESTAMP(3),
ADD COLUMN     "mensagem" TEXT,
ADD COLUMN     "responsabilidadeAceita" BOOLEAN NOT NULL DEFAULT false;
